#!/usr/bin/env python

# Created by Wazuh, Inc. <info@wazuh.com>.
# This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2

from wazuh.utils import execute, previous_month, cut_array, sort_array, search_array, tail
from wazuh import common
from datetime import datetime
import re


def status():
    """
    Returns the Manager processes that are running.
    :return: Array of dictionaries (keys: status, daemon).
    """

    return execute([common.ossec_control, '-j', 'status'])


def start():
    """
    Starts the OSSEC Manager processes.
    :return: Array of dictionaries (keys: status, daemon).
    """

    return execute([common.ossec_control, '-j', 'start'])


def stop():
    """
    Stops the OSSEC Manager processes.
    :return: Array of dictionaries (keys: status, daemon).
    """

    return execute([common.ossec_control, '-j', 'stop'])


def restart():
    """
    Restarts the OSSEC Manager processes.
    :return: Array of dictionaries (keys: status, daemon).
    """

    return execute([common.ossec_control, '-j', 'restart'])


def update_ruleset(type='both', force=False):
    """
    Updates the ruleset.

    :param type: Update: rules, rootchecks or both.
    :param force: Force update.
    :return: Dictionary generated by ossec_ruleset.py.
    """

    args = [common.ruleset_py, '--json', '--restart']

    if type == 'rules':
        args.append('--rules')
    elif type == 'rootchecks':
        args.append('--rootchecks')

    if force:
        args.append('--force-update')

    return execute(args)


def get_ruleset_backups():
    """
    Gets list of ruleset backups.

    :return: Array of backups IDs.
    """
    args = [common.ruleset_py, '--json', '--backups', 'list']

    return execute(args)['list']


def restore_ruleset_backups(date):
    """
    Restores a ruleset backup.

    :param date: Backup ID.
    :return: Dictionary generated by ossec_ruleset.py.
    """
    args = [common.ruleset_py, '--json', '--backups', date, '-s']

    return execute(args)


def __get_ossec_log_category(log):
    regex_category = re.compile("^\d\d\d\d/\d\d/\d\d\s\d\d:\d\d:\d\d\s(\S+):\s")

    match = re.search(regex_category, log)

    if match:
        category = match.group(1)

        if "rootcheck" in category:  # Unify rootcheck category
            category = "ossec-rootcheck"

        if "(" in category:  # Remove ()
            category = re.sub("\(\d\d\d\d\)", "", category)
    else:
        return None

    return category


def ossec_log(type_log='all', category='all', months=3, offset=0, limit=common.database_limit, sort=None, search=None):
    """
    Gets logs from ossec.log.

    :param type_log: Filters by log type: all, error or info.
    :param category: Filters by log category (i.e. ossec-remoted).
    :param months: Returns logs of the last n months. By default is 3 months.
    :param offset: First item to return.
    :param limit: Maximum number of items to return.
    :param sort: Sorts the items. Format: {"fields":["field1","field2"],"order":"asc|desc"}.
    :param search: Looks for items with the specified string.
    :return: Dictionary: {'items': array of items, 'totalItems': Number of items (without applying the limit)}
    """
    logs = []

    first_date = previous_month(months)
    statfs_error = "ERROR: statfs('******') produced error: No such file or directory"

    for line in tail(common.ossec_log, 2000):
        try:
            log_date = datetime.strptime(line[:10], '%Y/%m/%d')
        except ValueError:
            continue

        if log_date < first_date:
            continue

        if category != 'all':
            log_category = __get_ossec_log_category(line)

            if log_category:
                if log_category != category:
                    continue
            else:
                continue

        line = line.replace('\n', '')
        if type_log == 'all':
            logs.append(line)
        elif type_log == 'error' and "error:" in line.lower():
            if "ERROR: statfs(" in line:
                if statfs_error in logs:
                    continue
                else:
                    logs.append(statfs_error)
            else:
                logs.append(line)
        elif type_log == 'info' and "error:" not in line.lower():
            logs.append(line)

    if search:
        logs = search_array(logs, search['value'], search['negation'])

    if sort:
        logs = sort_array(logs, order=sort['order'])
    else:
        logs = sort_array(logs, order='desc')

    return {'items': cut_array(logs, offset, limit), 'totalItems': len(logs)}


def ossec_log_summary(months=3):
    """
    Summary of ossec.log.

    :param months: Check logs of the last n months. By default is 3 months.
    :return: Dictionary by categories.
    """
    categories = {}

    first_date = previous_month(months)

    with open(common.ossec_log) as f:

        for line in f:
            try:
                log_date = datetime.strptime(line[:10], '%Y/%m/%d')
            except ValueError:
                continue

            if log_date < first_date:
                continue

            category = __get_ossec_log_category(line)

            if category:
                if category in categories:
                    categories[category]['all'] += 1
                else:
                    categories[category] = {'all': 1, 'info': 0, 'error': 0}

                if "error" in line.lower():
                    categories[category]['error'] += 1
                else:
                    categories[category]['info'] += 1
            else:
                continue
    return categories
