#!/usr/bin/env python

# Created by Wazuh, Inc. <info@wazuh.com>.
# This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2

# Quick script to create an rst file from documentation generated by apidoc

# Requirements
# https
# Auth: foo:bar
# requests

import datetime
import json
import sys
import requests

TIMEOUT = 30  # cURL TIMEOUT. 0 to disable "example response"

### Hardcoded text ###
rst_header = '.. _api_reference:\n\n'
warning=f"\n.. Copyright (C) {datetime.datetime.now().year} Wazuh, Inc.\n.. Do not modify this file manually. It is generated automatically.\n\n"
introduction = "Reference\n======================\nThis API reference is organized by resources:\n\n{0}\nBelow is the `Request List`_ that shows all of the available requests.\n\n.. _request_list:\n"
str_request_list = 'Request List'
section_separator = '-'*40
subsection_separator = '+'*40
subsubsection_separator = '~'*60
str_request = '**Request**:'
str_parameter = '**Parameters:**'
str_example_req = '**Example Request:**'
str_example_res = '**Example Response:**'

hardcoded_items = {
        # GET - /manager/stats
        'GetManagerStats': {"error":0,"data":[{"hour":5,"firewall":0,"alerts":[{"times":4,"sigid":5715,"level":3},{"times":2,"sigid":1002,"level":2},{"...":"..."}],"totalAlerts":107,"syscheck":1257,"events":1483},{"...":"..."}]},

        # GET - /manager/stats/hourly
        'GetManagerStatsHourly': {"error":0,"data":{"averages":[100,357,242,500,422,"...",123],"interactions":0}},

        # GET - /manager/stats/weekly
        'GetManagerStatsWeekly': {"error":0,"data":{"Wed":{"hours":[223,"...",456],"interactions":0},"Sun":{"hours":[332,"...",313],"interactions":0},"Fri":{"hours":[131,"...",432],"interactions":0},"Tue":{"hours":[536,"...",345],"interactions":0},"Mon":{"hours":[444,"...",556],"interactions":0},"Thu":{"hours":[888,"...",123],"interactions":0},"Sat":{"hours":[134,"...",995],"interactions":0}}},

        # GET - /cluster/:node_id/stats
        'GetManagerStatsCluster': {"error":0,"data":[{"hour":5,"firewall":0,"alerts":[{"times":4,"sigid":5715,"level":3},{"times":2,"sigid":1002,"level":2},{"...":"..."}],"totalAlerts":107,"syscheck":1257,"events":1483},{"...":"..."}]},

        # GET - /cluster/:node_id/stats/hourly
        'GetManagerStatsHourlyCluster': {"error":0,"data":{"averages":[100,357,242,500,422,"...",123],"interactions":0}},

        # GET - /cluster/:node_id/stats/weekly
        'GetManagerStatsWeeklyCluster': {"error":0,"data":{"Wed":{"hours":[223,"...",456],"interactions":0},"Sun":{"hours":[332,"...",313],"interactions":0},"Fri":{"hours":[131,"...",432],"interactions":0},"Tue":{"hours":[536,"...",345],"interactions":0},"Mon":{"hours":[444,"...",556],"interactions":0},"Thu":{"hours":[888,"...",123],"interactions":0},"Sat":{"hours":[134,"...",995],"interactions":0}}},


        # PUT - /agents/restart
        'PutAgentsRestart': {"error":0,"data":"Restarting all agents"},

        # PUT - /agents/restart:agent_id
        'PutAgentsRestartId': {"error":0,"data":{"msg":"All selected agents were restarted","affected_agents":["007"]}},

        # DELETE - /rootcheck
        'DeleteRootcheck': {"error":0,"data":"Rootcheck database deleted"},

        # DELETE - /rootcheck/:agent_id
        'DeleteRootcheckAgentId': {"error":0,"data":"Rootcheck database deleted"},

        # DELETE - /syscheck
        'DeleteSyscheck': {"error":0,"data":"Syscheck database deleted"},

        # DELETE - /syscheck/:agent_id
        'DeleteSyscheckAgentId': {"error":0,"data":"Syscheck database deleted"},

        # PUT /syscheck
        'PutSyscheck' : {"error":0,"data":"Restarting Syscheck/Rootcheck on all agents"},

        # PUT /rootcheck
        'PutRootcheck' : {"error":0,"data":"Restarting Syscheck/Rootcheck on all agents"},

        # GET /agents/groups/:group_id/files/:filename
        'GetAgentGroupFile' : {"error":0,"data":{"controls":[{"...":"..."},{"reference":"CIS_Debian_Benchmark_v1.0pdf","name":"CIS - Testing against the CIS Debian Linux Benchmark v1","condition":"all required","checks":["f:/etc/debian_version;"]}]}},

        # GET /agents/outdated
        'GetOutdatedAgents' : {"error":0,"data":{"totalItems":2,"items":[{"version": "Wazuh v3.0.0","id": "003","name": "main_database"},{"version": "Wazuh v3.0.0","id": "004","name": "dmz002"}]}},

        # PUT /agents/:agent_id/upgrade
        'PutAgentsUpgradeId' : {"error": 0,"data": "Upgrade procedure started"},

        # PUT /agents/:agent_id/upgrade_custom
        'PutAgentsUpgradeCustomId' : {"error": 0,"data": "Installation started"},

        # GET /agents/:agent_id/upgrade_result
        'GetUpgradeResult' : {"error": 0,"data": "Agent upgraded successfully"},

        # POST /agents/restart
        'PostAgentListRestart' : {"error":0,"data":{"msg":"All selected agents were restarted","affected_agents":["002","004"]}},

        # GET /agents/purgeable/:timeframe
        'GetAgentsPurgeable' : {"error":0,"data":{"items":[{"id":"001","name":"test1"},{"id":"002","name":"test2"}],"timeframe":104400}},

        # POST /agents/purge
        'PostAgentsPurge' : {"error":0,"data":{"totalItems":2,"items":[{"id":"001","name":"test1"},{"id":"002","name":"test2"}],"timeframe":104400}},

        # GET /ciscat/:agent_id/results
        'GetCiscat_agent': {"error":0,"data":{"totalItems":2,"items":[{"profile":"xccdf_org.cisecurity.benchmarks_profile_Level_2_-_Server","scan":{"id":1406741147,"time":"2018-09-06T07:50:15.632-07:00"},"notchecked":36,"pass":104,"benchmark":"CIS Ubuntu Linux 16.04 LTS Benchmark","unknown":1,"score":57,"error":0,"fail":79},{"profile":"xccdf_org.cisecurity.benchmarks_profile_Level_1_-_Workstation","scan":{"id":1406741147,"time":"2018-09-06T07:50:52.630-07:00"},"notchecked":71,"pass":96,"benchmark":"CIS Ubuntu Linux 16.04 LTS Benchmark","unknown":0,"score":64,"error":0,"fail":53}]}},

        # GET /experimental/ciscat/results
        'GetCiscat': {"error":0,"data":{"totalItems":2,"items":[{"profile":"xccdf_org.cisecurity.benchmarks_profile_Level_1_-_Workstation","scan":{"id":1260865673,"time":"2018-09-06T07:59:25.682-07:00"},"notchecked":71,"pass":96,"benchmark":"CIS Ubuntu Linux 16.04 LTS Benchmark","unknown":0,"score":64,"agent_id":"001","error":0,"fail":53},{"profile":"xccdf_org.cisecurity.benchmarks_profile_Level_2_-_Server","scan":{"id":1260865673,"time":"2018-09-06T07:58:39.342-07:00"},"notchecked":36,"pass":104,"benchmark":"CIS Ubuntu Linux 16.04 LTS Benchmark","unknown":1,"score":57,"agent_id":"001","error":0,"fail":79}]}},

        # PUT /active-response/:agent_id
        'PutARAgentIdCommand': {"error":0,"data":"Command sent."},

        # POST /agents/group/:group_id/files/:file_name
        'PostAgentGroupFile': {"error":0,"data":"Agent configuration was updated successfully"},

        # POST /agents/group/:group_id/configuration
        'PostAgentGroupConfiguration': {"error":0,"data":"Agent configuration was updated successfully"},

        # POST /cluster/:node_id/files
        'PostUpdateFileCluster': {"error":0,"data":"File updated successfully"},

        # POST /manager/files
        'PostUpdateFile': {"error":0,"data":"File updated successfully"},

        # PUT /cluster/restart
        'PutRestartCluster': {"error":0,"data":"Restart request sent"},

        # PUT /cluster/:node_id/restart
        'PutRestartClusterNode': {"error":0,"data":"Restart request sent"},

        # PUT /manager/restart
        'PutRestartManager': {"error":0,"data":"Restart request sent"},

        # GET /cluster/:node_id/stats/analysisd
        'GetManagerStatsAnalysisdCluster': {"error": 0, "data": {"total_events_decoded": 10, "syscheck_events_decoded": 0, "syscheck_edps": 0, "syscollector_events_decoded": 0, "syscollector_edps": 0, "rootcheck_events_decoded": 0, "rootcheck_edps": 0, "sca_events_decoded": 0, "sca_edps": 0, "hostinfo_events_decoded": 0, "hostinfo_edps": 0, "winevt_events_decoded": 0, "winevt_edps": 0, "other_events_decoded": 10, "other_events_edps": 2, "events_processed": 10, "events_edps": 2, "events_received": 10, "events_dropped": 0, "alerts_written": 0, "firewall_written": 0, "fts_written": 0, "syscheck_queue_usage": 0, "syscheck_queue_size": 16384, "syscollector_queue_usage": 0, "syscollector_queue_size": 16384, "rootcheck_queue_usage": 0, "rootcheck_queue_size": 16384, "sca_queue_usage": 0, "sca_queue_size": 16384, "hostinfo_queue_usage": 0, "hostinfo_queue_size": 16384, "winevt_queue_usage": 0, "winevt_queue_size": 16384, "event_queue_usage": 0, "event_queue_size": 16384, "rule_matching_queue_usage": 0, "rule_matching_queue_size": 16384, "alerts_queue_usage": 0, "alerts_queue_size": 16384, "firewall_queue_usage": 0, "firewall_queue_size": 16384, "statistical_queue_usage": 0, "statistical_queue_size": 16384, "archives_queue_usage": 0, "archives_queue_size": 16384}},

        # GET /cluster/:node_id/stats/remoted
        'GetManagerStatsRemotedCluster': {"error": 0, "data": {"queue_size": 0, "total_queue_size": 131072, "tcp_sessions": 0, "evt_count": 3435, "ctrl_msg_count": 81, "discarded_count": 0, "msg_sent": 1087, "recv_bytes": 1004678, "dequeued_after_close": 0}}
    }
### ### ###


### Aux functions ###
try:
    from subprocess import check_output
except ImportError:
    def check_output(arguments, stdin=None, stderr=None, shell=False):
        temp_f = mkstemp()
        returncode = call(arguments, stdin=stdin, stdout=temp_f[0], stderr=stderr, shell=shell)
        close(temp_f[0])
        file_o = open(temp_f[1], 'r')
        cmd_output = file_o.read()
        file_o.close()
        remove(temp_f[1])

        if returncode != 0:
            error_cmd = CalledProcessError(returncode, arguments[0])
            error_cmd.output = cmd_output
            raise error_cmd
        else:
            return cmd_output

def insert_row(fields, sizes, highlight=False):
    row = ''
    for i in range(len(fields)):
        if i == 0 and highlight:
            row += '| ``' + fields[i] + '``' + ' '*(sizes[i]-len(fields[i])-1-2-2)
        elif i == 0 and fields[i] != 'Param' and fields[i] and fields[i] != ' ':
            row += '| ``' + fields[i] + '``' + ' '*(sizes[i]-len(fields[i])-1-2-2)
        else:
            row += '| ' + fields[i] + ' '*(sizes[i]-len(fields[i])-1)
    row += '|' +'\n'

    return row

def insert_separator(sizes, sep='-'):
    row = ''
    for size in sizes:
        row += '+' + sep*size
    row += '+' +'\n'

    return row

def create_table(headers, rows, sizes):
    output = ''
    output += insert_separator(sizes)
    output += insert_row(headers, sizes)
    output += insert_separator(sizes, '=')
    for row in rows:
        fields = [row['field'], row['type'], row['description'].replace('<p>', '').replace('</p>', '')]
        output += insert_row(fields, sizes, not row['optional'])

        if 'allowedValues' in row:
            output += insert_row([' ', ' ', ' '], sizes)
            output += insert_row([' ', ' ', 'Allowed values:'], sizes)
            output += insert_row([' ', ' ', ' '], sizes)
            for value in row['allowedValues']:
                output += insert_row([' ', ' ', '- {0}'.format(value[1:-1])], sizes)

        output += insert_separator(sizes)
    return output


def prepare_environment():
    """
    Sets up documentation required environment
    """
    agents_to_add = [
        ("server001","10.0.0.62"),
        ("dmz001","10.0.0.12"),
        ("main_database","10.0.0.15"),
        ("dmz002","10.0.0.14"),
        ("server002","10.0.0.20")
    ]
    for name,ip in agents_to_add:
        requests.post("https://127.0.0.1:55000/agents", auth=('foo','bar'), data={"name":name,"ip":ip}, verify=False)
    
    groups_to_create = ["dmz","webserver","database"]
    for group in groups_to_create:
        requests.put("https://127.0.0.1:55000/agents/groups/"+group, auth=('foo','bar'), verify=False)
    
    agents_groups = [
        ("001","dmz"),
        ("002","webserver"),
        ("003","database"),
        ("004","dmz"),
        ("005","webserver")
    ]
    for a_id, g_id in agents_groups:
        requests.put("https://127.0.0.1:55000/agents/{}/group/{}".format(a_id, g_id), auth=('foo','bar'), verify=False)

    dmz_conf = b'<agent_config os="Linux">\n<localfile>\n<location>/var/log/linux.log</location>\n<log_format>syslog</log_format>\n</localfile>\n</agent_config>\n'
    requests.post("https://127.0.0.1:55000/agents/groups/dmz/configuration", auth=('foo', 'bar'), verify=False, data=dmz_conf, headers={'Content-Type': 'application/xml'})

def clean_environment():
    """
    Cleans generated environment in case the docs need to be generated more times
    """
    requests.delete("https://127.0.0.1:55000/agents", auth=("foo","bar"), params={"older_than":"1s","status":"neverconnected","purge":"true"}, verify=False)
    requests.delete("https://127.0.0.1:55000/agents/groups", auth=("foo","bar"), data={"ids":["dmz","webserver","database","pciserver"]}, verify=False)

### ### ###

if __name__ == "__main__":
    prepare_environment()

    alerts = []
    hardcoded = []
    docu_file_json = './build/html/api_data.json'

    # Generate docu with apidoc
    try:
        # wazuh-api: apidoc -i ../ -o ./build/html -c . -f js -e node_modules
        output = check_output(['apidoc', '-i', '../', '-o', './build/html', '-c', '.', '-f', 'js', '-e', 'node_modules']).decode('utf-8')
        print("\nAPIDOC:")
        print(output)
        with open(docu_file_json) as data_file:
            docu = json.load(data_file)
    except Exception as e:
        print("Error: {0}".format(e))
        sys.exit(1)

    # Group by section and subsection
    sections = {}
    request_list = {}

    for req in docu:
        ss = req['group']  # subsection
        if ss.startswith('_'):
            continue

        s = req['filename'].split('/')[-1][:-3].replace('_', ' ')  # section

        if s not in sections:
            sections[s] = {}
            request_list[s] = []

        if ss in sections[s]:
            sections[s][ss].append(req)
        else:
            sections[s][ss] = [req]

        request_list[s].append(['{0} {1}'.format(req['type'].upper(), req['url']), req['title']])

    # Generate RST
    try:
        rst_output = sys.argv[1]
    except:
        rst_output = './build/api_reference.rst'

    print("\nOutput:")
    print(rst_output + '\n')
    f = open(rst_output, 'w')

    # Header
    f.write(warning)
    f.write(rst_header)

    # Introduction
    secs = ""
    for req in sorted(request_list.keys()):
        secs += '* `{0}`_\n'.format(req.title())
    f.write(introduction.format(secs))

    # Request list
    f.write('\n{0}\n'.format(str_request_list))
    f.write('---------------------------------' + '\n\n')
    for req in sorted(request_list.keys()):
        f.write('`{0}`_\n'.format(req.title()))
        for item in sorted(request_list[req]):
            f.write('\t* {0}  (`{1}`_)\n'.format(item[0], item[1]))
        f.write('\n')

    for s in sorted(sections.keys()):
        print(s.title())

        # Section
        f.write(s.title() + '\n')
        f.write(section_separator + '\n')

        for ss in sorted(sections[s].keys()):
            print('\t' + ss)

            # Subsection
            f.write(ss + '\n')
            f.write(subsection_separator + '\n\n')

            for item in sorted(sections[s][ss], key = lambda o: o.get('title')):
                print('\t\t{0} - {1}'.format(item['type'].upper(), item['url']))

                # Title and description
                f.write(item['title'] + '\n')
                f.write(subsubsection_separator + '\n')
                f.write(item['description'].replace('<p>', '').replace('</p>', '') + '\n')

                # Request
                f.write('\n{0}\n\n'.format(str_request))
                f.write('``{0}`` ::\n\n\t{1}\n'.format(item['type'].upper(), item['url']))

                # Parameters
                if 'parameter' in item:
                    rows = []
                    f.write('\n{0}\n\n'.format(str_parameter))
                    params = item['parameter']['fields']['Parameter']
                    table = create_table(['Param', 'Type', 'Description'], params, [30, 15, 230])
                    f.write(table)
                f.write('\n')

                # Examples
                msg_end = '\t{0} - {1}'.format(item['type'].upper(), item['url'])
                for example in item['examples']:
                    # Example Request
                    f.write(str_example_req + '\n')
                    f.write('::\n')
                    f.write('\n\t{0}\n\n'.format(example['content']))

                    # Example Response
                    if TIMEOUT != 0:
                        hardcoded_output = True if '*' in example['title'] else False

                        if hardcoded_output:
                            item_id = item['name']
                            if item_id in hardcoded_items:
                                output = json.dumps(hardcoded_items[item_id], indent=4)
                                hardcoded.append(msg_end)
                            else:
                                output = "ToDo - Hardcoded output\n"
                                alerts.append(msg_end + " -> " + output)
                        else:
                            try:
                                # Prepare command
                                command = []
                                for arg in example['content'].split(' '):
                                    start = 0
                                    end = len(arg)

                                    if arg[0] == '\'' or arg[0] == '"':
                                        start += 1
                                    if arg[-1] == '\'' or arg[-1] == '"':
                                        end -= 1

                                    command.append(arg[start:end])

                                command.extend(['--connect-timeout', str(TIMEOUT)])

                                # Get request output
                                output = check_output(command).decode('utf-8')
                            except Exception as e:
                                output = "ToDo - Error output\n"
                                alerts.append(msg_end + " -> " + output)
                    else:
                        output = "ToDo - Testing\n"
                        alerts.append(msg_end + " -> " + output)

                    f.write(str_example_res + '\n')
                    f.write('::\n')
                    for line in output.split('\n'):
                        f.write('\n\t{0}'.format(line))
                    f.write('\n')
                    # End Example Response

                f.write('\n')  # for examples
            f.write('\n')  # for item in subsection
        f.write('\n')  # for subsection

    f.close()

    clean_environment()

    if hardcoded:
        print("\n\nHardcoded items:\n")
        for hc in hardcoded:
            print(hc)

    if alerts:
        print('\n\n' + '*'*50)
        print("There are no example responses for these requests:\n")
        for alert in alerts:
            print(alert)
        print('*'*50)

    print("\nDone.\n\n")
