#!/usr/bin/env python
import json
from sys import exit
from wazuh.agent import Agent
from wazuh.exception import WazuhException

agent = Agent()

try:
    agent_id = agent.add('WazuhTestAgent', 'Any')
except WazuhException as e:
    print("Error {0}: {1}.".format(e.code, e.message))
    exit(1)

agent_key = agent.get_key()
print("\nAgent added with:\n\tID: {0}\n\tKey: {1}".format(agent_id, agent_key))

agent.get()  # Load information generated by OSSEC
print("\nAgent info:")
print(json.dumps(agent.to_dict(), indent=4, sort_keys=True))
